services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    image: ghcr.io/songdaopi/freeclaude:lasted
    ports:
      - "7860:8080"
    environment:
      NODE_ENV: production
    restart: unless-stopped  # 自动重启
